name: flask workflow

#triggers
on:
    push:
        branches: ["master","main"]
    pull_request:
        branches: ["master","main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: install dependencies
      run: |
        pip install flask
        pip install flask
    
    - name: run test
      run: |
        pytest
    
    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    
    
    
